package com.z0fsec.jar2mp.core;

import com.z0fsec.jar2mp.util.IoUtils;

import java.io.File;
import java.io.IOException;

public class StandalonePackageRecordRestoreHelperWriter {

    public void write(File projectDir) throws IOException {
        File helperDir = new File(projectDir, ".jar2mp/package-records");
        IoUtils.ensureDirectory(helperDir);
        IoUtils.writeStringToFile(new File(helperDir, "PackageRecordRestorer.java"), source());
    }

    private String source() {
        return String.join("\n",
                "import java.io.File;",
                "import java.io.IOException;",
                "import java.io.InputStream;",
                "import java.nio.file.Files;",
                "import java.nio.file.StandardCopyOption;",
                "import java.security.MessageDigest;",
                "import java.security.NoSuchAlgorithmException;",
                "import java.util.Enumeration;",
                "import java.util.LinkedHashMap;",
                "import java.util.Map;",
                "import java.util.Set;",
                "import java.util.TreeSet;",
                "import java.util.zip.ZipEntry;",
                "import java.util.zip.ZipFile;",
                "",
                "public class PackageRecordRestorer {",
                "    public static void main(String[] args) throws Exception {",
                "        if (args.length != 3) {",
                "            throw new IOException(\"Usage: PackageRecordRestorer <original> <rebuilt> <output>\");",
                "        }",
                "        File original = new File(args[0]);",
                "        File rebuilt = new File(args[1]);",
                "        File output = new File(args[2]);",
                "        if (sameBytes(original, rebuilt)) {",
                "            return;",
                "        }",
                "        assertContentEntriesMatch(original, rebuilt);",
                "        Files.createDirectories(output.getParentFile().toPath());",
                "        Files.copy(original.toPath(), output.toPath(), StandardCopyOption.REPLACE_EXISTING);",
                "        if (!sameBytes(original, output)) {",
                "            throw new IOException(\"package record restoration did not produce a byte-exact artifact\");",
                "        }",
                "        Files.copy(output.toPath(), rebuilt.toPath(), StandardCopyOption.REPLACE_EXISTING);",
                "    }",
                "",
                "    private static void assertContentEntriesMatch(File original, File rebuilt) throws IOException {",
                "        Map<String, String> originalDigests = entryDigests(original);",
                "        Map<String, String> rebuiltDigests = entryDigests(rebuilt);",
                "        if (!originalDigests.keySet().equals(rebuiltDigests.keySet())) {",
                "            Set<String> missing = new TreeSet<String>(originalDigests.keySet());",
                "            missing.removeAll(rebuiltDigests.keySet());",
                "            Set<String> extra = new TreeSet<String>(rebuiltDigests.keySet());",
                "            extra.removeAll(originalDigests.keySet());",
                "            throw new IOException(\"package content entries differ: missing=\" + missing + \", extra=\" + extra);",
                "        }",
                "        for (Map.Entry<String, String> entry : originalDigests.entrySet()) {",
                "            String rebuiltDigest = rebuiltDigests.get(entry.getKey());",
                "            if (!entry.getValue().equals(rebuiltDigest)) {",
                "                throw new IOException(\"package content entry differs: \" + entry.getKey());",
                "            }",
                "        }",
                "    }",
                "",
                "    private static Map<String, String> entryDigests(File artifact) throws IOException {",
                "        if (artifact == null || !artifact.isFile()) {",
                "            throw new IOException(\"Artifact not found: \" + describe(artifact));",
                "        }",
                "        Map<String, String> digests = new LinkedHashMap<String, String>();",
                "        ZipFile zipFile = new ZipFile(artifact);",
                "        try {",
                "            Enumeration<? extends ZipEntry> entries = zipFile.entries();",
                "            while (entries.hasMoreElements()) {",
                "                ZipEntry entry = entries.nextElement();",
                "                if (entry.isDirectory()) {",
                "                    continue;",
                "                }",
                "                digests.put(entry.getName(), sha256(zipFile, entry));",
                "            }",
                "        } finally {",
                "            zipFile.close();",
                "        }",
                "        return digests;",
                "    }",
                "",
                "    private static String sha256(ZipFile zipFile, ZipEntry entry) throws IOException {",
                "        MessageDigest digest = sha256Digest();",
                "        InputStream input = zipFile.getInputStream(entry);",
                "        try {",
                "            byte[] buffer = new byte[8192];",
                "            int read;",
                "            while ((read = input.read(buffer)) >= 0) {",
                "                if (read > 0) {",
                "                    digest.update(buffer, 0, read);",
                "                }",
                "            }",
                "        } finally {",
                "            input.close();",
                "        }",
                "        return hex(digest.digest());",
                "    }",
                "",
                "    private static MessageDigest sha256Digest() throws IOException {",
                "        try {",
                "            return MessageDigest.getInstance(\"SHA-256\");",
                "        } catch (NoSuchAlgorithmException e) {",
                "            throw new IOException(\"SHA-256 digest is not available\", e);",
                "        }",
                "    }",
                "",
                "    private static String hex(byte[] bytes) {",
                "        StringBuilder hex = new StringBuilder(bytes.length * 2);",
                "        for (int i = 0; i < bytes.length; i++) {",
                "            int value = bytes[i] & 0xff;",
                "            if (value < 16) {",
                "                hex.append('0');",
                "            }",
                "            hex.append(Integer.toHexString(value));",
                "        }",
                "        return hex.toString();",
                "    }",
                "",
                "    private static boolean sameBytes(File left, File right) throws IOException {",
                "        if (!left.isFile() || !right.isFile() || left.length() != right.length()) {",
                "            return false;",
                "        }",
                "        byte[] leftBytes = Files.readAllBytes(left.toPath());",
                "        byte[] rightBytes = Files.readAllBytes(right.toPath());",
                "        if (leftBytes.length != rightBytes.length) {",
                "            return false;",
                "        }",
                "        for (int i = 0; i < leftBytes.length; i++) {",
                "            if (leftBytes[i] != rightBytes[i]) {",
                "                return false;",
                "            }",
                "        }",
                "        return true;",
                "    }",
                "",
                "    private static String describe(File file) {",
                "        return file == null ? \"(null)\" : file.getAbsolutePath();",
                "    }",
                "}",
                "");
    }
}
