package com.z0fsec.jar2mp.core;

import com.z0fsec.jar2mp.util.IoUtils;

import java.io.File;
import java.io.IOException;

public class StandaloneByteExactPackageHelperWriter {

    public void write(File projectDir) throws IOException {
        File helperDir = new File(projectDir, ".jar2mp/byte-exact");
        IoUtils.ensureDirectory(helperDir);
        IoUtils.writeStringToFile(new File(helperDir, "ByteExactPackageRestorer.java"), source());
    }

    private String source() {
        return String.join("\n",
                "import java.io.ByteArrayOutputStream;",
                "import java.io.File;",
                "import java.io.IOException;",
                "import java.nio.charset.StandardCharsets;",
                "import java.nio.file.Files;",
                "import java.nio.file.StandardCopyOption;",
                "import java.util.ArrayList;",
                "import java.util.Collections;",
                "import java.util.Comparator;",
                "import java.util.HashSet;",
                "import java.util.LinkedHashMap;",
                "import java.util.List;",
                "import java.util.Map;",
                "import java.util.Set;",
                "",
                "public class ByteExactPackageRestorer {",
                "    private static final long LOCAL_FILE_HEADER_SIGNATURE = 0x04034b50L;",
                "    private static final long CENTRAL_FILE_HEADER_SIGNATURE = 0x02014b50L;",
                "    private static final long END_OF_CENTRAL_DIRECTORY_SIGNATURE = 0x06054b50L;",
                "    private static final long ZIP64_MARKER = 0xffffffffL;",
                "    private static final int ZIP64_ENTRY_COUNT_MARKER = 0xffff;",
                "    private static final String MANIFEST_ENTRY = \"META-INF/MANIFEST.MF\";",
                "",
                "    public static void main(String[] args) throws Exception {",
                "        if (args.length != 3) {",
                "            throw new IOException(\"Usage: ByteExactPackageRestorer <original> <rebuilt> <output>\");",
                "        }",
                "        File original = new File(args[0]);",
                "        File rebuilt = new File(args[1]);",
                "        File output = new File(args[2]);",
                "        if (sameBytes(original, rebuilt)) {",
                "            return;",
                "        }",
                "        restore(original, rebuilt, output);",
                "        if (!sameBytes(original, output)) {",
                "            throw new IOException(\"record-level ZIP restoration did not produce a byte-exact package\");",
                "        }",
                "        Files.copy(output.toPath(), rebuilt.toPath(), StandardCopyOption.REPLACE_EXISTING);",
                "    }",
                "",
                "    private static void restore(File originalArtifact, File rebuiltArtifact, File restored) throws IOException {",
                "        if (originalArtifact == null || !originalArtifact.isFile()) {",
                "            throw new IOException(\"Original artifact not found: \" + describe(originalArtifact));",
                "        }",
                "        if (rebuiltArtifact == null || !rebuiltArtifact.isFile()) {",
                "            throw new IOException(\"Rebuilt artifact not found: \" + describe(rebuiltArtifact));",
                "        }",
                "        ZipLayout original = ZipLayout.read(originalArtifact);",
                "        ZipLayout rebuilt = ZipLayout.read(rebuiltArtifact);",
                "        validateSameEntrySet(original, rebuilt);",
                "        Files.createDirectories(restored.getParentFile().toPath());",
                "        ByteArrayOutputStream output = new ByteArrayOutputStream(rebuilt.bytes.length);",
                "        Map<String, Long> newOffsets = new LinkedHashMap<String, Long>();",
                "        for (String name : original.entryOrder) {",
                "            newOffsets.put(name, Long.valueOf(output.size()));",
                "            output.write(selectRestoredLocalRecord(original, rebuilt, name));",
                "        }",
                "        long centralDirectoryOffset = output.size();",
                "        for (String name : original.entryOrder) {",
                "            byte[] centralRecord = selectRestoredCentralRecord(original, rebuilt, name);",
                "            writeUInt32(centralRecord, 42, newOffsets.get(name).longValue());",
                "            output.write(centralRecord);",
                "        }",
                "        long centralDirectorySize = output.size() - centralDirectoryOffset;",
                "        byte[] eocd = rebuilt.endOfCentralDirectory.clone();",
                "        writeUInt16(eocd, 8, original.entryOrder.size());",
                "        writeUInt16(eocd, 10, original.entryOrder.size());",
                "        writeUInt32(eocd, 12, centralDirectorySize);",
                "        writeUInt32(eocd, 16, centralDirectoryOffset);",
                "        output.write(eocd);",
                "        Files.write(restored.toPath(), output.toByteArray());",
                "    }",
                "",
                "    private static void validateSameEntrySet(ZipLayout original, ZipLayout rebuilt) throws IOException {",
                "        Set<String> originalNames = new HashSet<String>(original.entryOrder);",
                "        Set<String> rebuiltNames = new HashSet<String>(rebuilt.entryOrder);",
                "        for (String name : originalNames) {",
                "            if (!rebuiltNames.contains(name) && !original.isEmptyDirectoryEntry(name)) {",
                "                throw new IOException(\"Original entry is missing from rebuilt package: \" + name);",
                "            }",
                "        }",
                "        for (String name : rebuiltNames) {",
                "            if (!originalNames.contains(name) && !rebuilt.isEmptyDirectoryEntry(name)) {",
                "                throw new IOException(\"Rebuilt package has extra entry: \" + name);",
                "            }",
                "        }",
                "    }",
                "",
                "    private static byte[] selectRestoredLocalRecord(ZipLayout original, ZipLayout rebuilt, String name) {",
                "        if (original.isEmptyDirectoryEntry(name) || !rebuilt.localRecords.containsKey(name)) {",
                "            return original.localRecords.get(name).clone();",
                "        }",
                "        if (usesOriginalPayload(original, rebuilt, name)) {",
                "            return original.localRecords.get(name).clone();",
                "        }",
                "        byte[] restoredRecord = restoreLocalRecordMetadata(original, rebuilt, name);",
                "        if (restoredRecord != null) {",
                "            return restoredRecord;",
                "        }",
                "        byte[] localRecord = rebuilt.localRecords.get(name).clone();",
                "        copyDosTimestamp(original.localRecords.get(name), 10, localRecord, 10);",
                "        copyExtraFieldIfSameLength(original.localRecords.get(name), localRecord, 26, 28, 30);",
                "        return localRecord;",
                "    }",
                "",
                "    private static byte[] selectRestoredCentralRecord(ZipLayout original, ZipLayout rebuilt, String name) {",
                "        if (original.isEmptyDirectoryEntry(name) || !rebuilt.centralRecords.containsKey(name)) {",
                "            return original.centralRecords.get(name).clone();",
                "        }",
                "        if (usesOriginalPayload(original, rebuilt, name)) {",
                "            return original.centralRecords.get(name).clone();",
                "        }",
                "        if (compressedSizesMatch(original, rebuilt, name)) {",
                "            return original.centralRecords.get(name).clone();",
                "        }",
                "        byte[] centralRecord = rebuilt.centralRecords.get(name).clone();",
                "        copyDosTimestamp(original.centralRecords.get(name), 12, centralRecord, 12);",
                "        copyExtraFieldIfSameLength(original.centralRecords.get(name), centralRecord, 28, 30, 46);",
                "        return centralRecord;",
                "    }",
                "",
                "    private static byte[] restoreLocalRecordMetadata(ZipLayout original, ZipLayout rebuilt, String name) {",
                "        if (!compressedSizesMatch(original, rebuilt, name)) {",
                "            return null;",
                "        }",
                "        byte[] originalRecord = original.localRecords.get(name);",
                "        byte[] rebuiltRecord = rebuilt.localRecords.get(name);",
                "        int originalDataStart = localDataStart(originalRecord);",
                "        int rebuiltDataStart = localDataStart(rebuiltRecord);",
                "        int compressedSize = compressedSizeAsInt(original.centralRecords.get(name));",
                "        if (compressedSize < 0) {",
                "            return null;",
                "        }",
                "        int rebuiltDataEnd = rebuiltDataStart + compressedSize;",
                "        if (rebuiltDataEnd > rebuiltRecord.length || originalDataStart + compressedSize > originalRecord.length) {",
                "            return null;",
                "        }",
                "        int originalDescriptorStart = originalDataStart + compressedSize;",
                "        ByteArrayOutputStream output = new ByteArrayOutputStream(originalDataStart + compressedSize + originalRecord.length - originalDescriptorStart);",
                "        output.write(originalRecord, 0, originalDataStart);",
                "        output.write(rebuiltRecord, rebuiltDataStart, compressedSize);",
                "        output.write(originalRecord, originalDescriptorStart, originalRecord.length - originalDescriptorStart);",
                "        return output.toByteArray();",
                "    }",
                "",
                "    private static boolean compressedSizesMatch(ZipLayout original, ZipLayout rebuilt, String name) {",
                "        byte[] originalCentralRecord = original.centralRecords.get(name);",
                "        byte[] rebuiltCentralRecord = rebuilt.centralRecords.get(name);",
                "        return originalCentralRecord != null && rebuiltCentralRecord != null && readUInt32(originalCentralRecord, 20) == readUInt32(rebuiltCentralRecord, 20);",
                "    }",
                "",
                "    private static int localDataStart(byte[] localRecord) {",
                "        return 30 + readUInt16(localRecord, 26) + readUInt16(localRecord, 28);",
                "    }",
                "",
                "    private static int compressedSizeAsInt(byte[] centralRecord) {",
                "        long compressedSize = readUInt32(centralRecord, 20);",
                "        return compressedSize > Integer.MAX_VALUE ? -1 : (int) compressedSize;",
                "    }",
                "",
                "    private static boolean usesOriginalPayload(ZipLayout original, ZipLayout rebuilt, String name) {",
                "        return MANIFEST_ENTRY.equals(name) || isModuleInfoEntry(name) || payloadIdentityMatches(original, rebuilt, name);",
                "    }",
                "",
                "    private static boolean isModuleInfoEntry(String name) {",
                "        return \"module-info.class\".equals(name) || (name != null && name.endsWith(\"/module-info.class\"));",
                "    }",
                "",
                "    private static boolean payloadIdentityMatches(ZipLayout original, ZipLayout rebuilt, String name) {",
                "        byte[] originalCentralRecord = original.centralRecords.get(name);",
                "        byte[] rebuiltCentralRecord = rebuilt.centralRecords.get(name);",
                "        return originalCentralRecord != null && rebuiltCentralRecord != null && readUInt32(originalCentralRecord, 16) == readUInt32(rebuiltCentralRecord, 16) && readUInt32(originalCentralRecord, 24) == readUInt32(rebuiltCentralRecord, 24);",
                "    }",
                "",
                "    private static void copyDosTimestamp(byte[] source, int sourceOffset, byte[] target, int targetOffset) {",
                "        target[targetOffset] = source[sourceOffset];",
                "        target[targetOffset + 1] = source[sourceOffset + 1];",
                "        target[targetOffset + 2] = source[sourceOffset + 2];",
                "        target[targetOffset + 3] = source[sourceOffset + 3];",
                "    }",
                "",
                "    private static void copyExtraFieldIfSameLength(byte[] source, byte[] target, int nameLengthOffset, int extraLengthOffset, int dataOffset) {",
                "        int sourceNameLength = readUInt16(source, nameLengthOffset);",
                "        int sourceExtraLength = readUInt16(source, extraLengthOffset);",
                "        int targetNameLength = readUInt16(target, nameLengthOffset);",
                "        int targetExtraLength = readUInt16(target, extraLengthOffset);",
                "        if (sourceExtraLength != targetExtraLength) {",
                "            return;",
                "        }",
                "        System.arraycopy(source, dataOffset + sourceNameLength, target, dataOffset + targetNameLength, sourceExtraLength);",
                "    }",
                "",
                "    private static long readUInt32(byte[] data, int offset) {",
                "        return ((long) data[offset] & 0xff) | (((long) data[offset + 1] & 0xff) << 8) | (((long) data[offset + 2] & 0xff) << 16) | (((long) data[offset + 3] & 0xff) << 24);",
                "    }",
                "",
                "    private static int readUInt16(byte[] data, int offset) {",
                "        return (data[offset] & 0xff) | ((data[offset + 1] & 0xff) << 8);",
                "    }",
                "",
                "    private static void writeUInt16(byte[] data, int offset, int value) {",
                "        data[offset] = (byte) (value & 0xff);",
                "        data[offset + 1] = (byte) ((value >>> 8) & 0xff);",
                "    }",
                "",
                "    private static void writeUInt32(byte[] data, int offset, long value) {",
                "        data[offset] = (byte) (value & 0xff);",
                "        data[offset + 1] = (byte) ((value >>> 8) & 0xff);",
                "        data[offset + 2] = (byte) ((value >>> 16) & 0xff);",
                "        data[offset + 3] = (byte) ((value >>> 24) & 0xff);",
                "    }",
                "",
                "    private static boolean sameBytes(File left, File right) throws IOException {",
                "        if (!left.isFile() || !right.isFile() || left.length() != right.length()) {",
                "            return false;",
                "        }",
                "        byte[] leftBytes = Files.readAllBytes(left.toPath());",
                "        byte[] rightBytes = Files.readAllBytes(right.toPath());",
                "        if (leftBytes.length != rightBytes.length) {",
                "            return false;",
                "        }",
                "        for (int i = 0; i < leftBytes.length; i++) {",
                "            if (leftBytes[i] != rightBytes[i]) {",
                "                return false;",
                "            }",
                "        }",
                "        return true;",
                "    }",
                "",
                "    private static String describe(File file) {",
                "        return file == null ? \"(null)\" : file.getAbsolutePath();",
                "    }",
                "",
                "    private static class ZipLayout {",
                "        private final byte[] bytes;",
                "        private final List<String> entryOrder = new ArrayList<String>();",
                "        private final Map<String, byte[]> centralRecords = new LinkedHashMap<String, byte[]>();",
                "        private final Map<String, byte[]> localRecords = new LinkedHashMap<String, byte[]>();",
                "        private byte[] endOfCentralDirectory;",
                "",
                "        private ZipLayout(byte[] bytes) {",
                "            this.bytes = bytes;",
                "        }",
                "",
                "        private static ZipLayout read(File file) throws IOException {",
                "            ZipLayout layout = new ZipLayout(Files.readAllBytes(file.toPath()));",
                "            int eocdOffset = findEndOfCentralDirectory(layout.bytes);",
                "            layout.endOfCentralDirectory = copy(layout.bytes, eocdOffset, layout.bytes.length);",
                "            int totalEntries = readUInt16(layout.bytes, eocdOffset + 10);",
                "            long centralDirectorySize = readUInt32(layout.bytes, eocdOffset + 12);",
                "            long centralDirectoryOffset = readUInt32(layout.bytes, eocdOffset + 16);",
                "            if (totalEntries == ZIP64_ENTRY_COUNT_MARKER || centralDirectorySize == ZIP64_MARKER || centralDirectoryOffset == ZIP64_MARKER) {",
                "                throw new IOException(\"ZIP64 archives are not supported for byte-exact package restoration yet.\");",
                "            }",
                "            if (centralDirectoryOffset > Integer.MAX_VALUE || centralDirectorySize > Integer.MAX_VALUE) {",
                "                throw new IOException(\"ZIP central directory is too large to restore in memory.\");",
                "            }",
                "            Map<String, Long> localOffsets = layout.readCentralDirectory((int) centralDirectoryOffset, totalEntries);",
                "            layout.readLocalRecords(localOffsets, (int) centralDirectoryOffset);",
                "            return layout;",
                "        }",
                "",
                "        private Map<String, Long> readCentralDirectory(int centralDirectoryOffset, int totalEntries) throws IOException {",
                "            Map<String, Long> localOffsets = new LinkedHashMap<String, Long>();",
                "            int position = centralDirectoryOffset;",
                "            for (int i = 0; i < totalEntries; i++) {",
                "                if (readUInt32(bytes, position) != CENTRAL_FILE_HEADER_SIGNATURE) {",
                "                    throw new IOException(\"Invalid ZIP central directory entry at offset \" + position);",
                "                }",
                "                int nameLength = readUInt16(bytes, position + 28);",
                "                int extraLength = readUInt16(bytes, position + 30);",
                "                int commentLength = readUInt16(bytes, position + 32);",
                "                int recordEnd = position + 46 + nameLength + extraLength + commentLength;",
                "                String name = new String(bytes, position + 46, nameLength, StandardCharsets.UTF_8);",
                "                if (centralRecords.containsKey(name)) {",
                "                    throw new IOException(\"Duplicate ZIP entry names are not supported: \" + name);",
                "                }",
                "                entryOrder.add(name);",
                "                centralRecords.put(name, copy(bytes, position, recordEnd));",
                "                localOffsets.put(name, Long.valueOf(readUInt32(bytes, position + 42)));",
                "                position = recordEnd;",
                "            }",
                "            return localOffsets;",
                "        }",
                "",
                "        private void readLocalRecords(Map<String, Long> localOffsets, int centralDirectoryOffset) throws IOException {",
                "            List<Map.Entry<String, Long>> offsets = new ArrayList<Map.Entry<String, Long>>(localOffsets.entrySet());",
                "            Collections.sort(offsets, new Comparator<Map.Entry<String, Long>>() {",
                "                public int compare(Map.Entry<String, Long> left, Map.Entry<String, Long> right) {",
                "                    return left.getValue().compareTo(right.getValue());",
                "                }",
                "            });",
                "            for (int i = 0; i < offsets.size(); i++) {",
                "                String name = offsets.get(i).getKey();",
                "                long start = offsets.get(i).getValue().longValue();",
                "                long end = i + 1 < offsets.size() ? offsets.get(i + 1).getValue().longValue() : centralDirectoryOffset;",
                "                if (start > Integer.MAX_VALUE || end > Integer.MAX_VALUE || start < 0 || end < start) {",
                "                    throw new IOException(\"Invalid ZIP local record offsets for \" + name);",
                "                }",
                "                if (readUInt32(bytes, (int) start) != LOCAL_FILE_HEADER_SIGNATURE) {",
                "                    throw new IOException(\"Invalid ZIP local file header for \" + name);",
                "                }",
                "                localRecords.put(name, copy(bytes, (int) start, (int) end));",
                "            }",
                "        }",
                "",
                "        private boolean isEmptyDirectoryEntry(String name) {",
                "            byte[] centralRecord = centralRecords.get(name);",
                "            return name.endsWith(\"/\") && centralRecord != null && readUInt32(centralRecord, 16) == 0L && readUInt32(centralRecord, 24) == 0L;",
                "        }",
                "",
                "        private static int findEndOfCentralDirectory(byte[] data) throws IOException {",
                "            int minimum = Math.max(0, data.length - 65557);",
                "            for (int i = data.length - 22; i >= minimum; i--) {",
                "                if (readUInt32(data, i) == END_OF_CENTRAL_DIRECTORY_SIGNATURE) {",
                "                    return i;",
                "                }",
                "            }",
                "            throw new IOException(\"ZIP end of central directory not found.\");",
                "        }",
                "",
                "        private static byte[] copy(byte[] source, int start, int end) {",
                "            byte[] result = new byte[end - start];",
                "            System.arraycopy(source, start, result, 0, result.length);",
                "            return result;",
                "        }",
                "    }",
                "}",
                "");
    }
}
